name: "Deploy para a VPS"

on:
  push:
    branches:
      - main

jobs: 
  build_deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para a VPS"
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --exclude='.env'"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.API_READOVER_TARGET }}

      - name: "Build e permissões"
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            set -e
            
            echo "API_READOVER_TARGET is $API_READOVER_TARGET"
            
            cd "$API_READOVER_TARGET/../"
            
            sudo chown -R lsadm:lsadm $API_READOVER_TARGET
            sudo find $API_READOVER_TARGET -type d -exec chmod 755 {} \;
            sudo find $API_READOVER_TARGET -type f -exec chmod 644 {} \;
            
            npm install
            npm run prod
          EOF
